
[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml"]

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 300

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true

[font]
size = 12.8

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"


[keyboard]
bindings = [
  { key = "Left",  mods = "Command", action = "SelectPreviousTab" },
  { key = "Right", mods = "Command", action = "SelectNextTab" },
  { key = "K",     mods = "Command", action = "ClearHistory" },
  { key = "K",     mods = "Command", chars = "\u000c" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Key0",  mods = "Alt", chars = "º" },
  { key = "Key1",  mods = "Alt", chars = "¡" },
  { key = "Key2",  mods = "Alt", chars = "€" },
  { key = "Key3",  mods = "Alt", chars = "#" },
  { key = "Key4",  mods = "Alt", chars = "¢" },
  { key = "Key5",  mods = "Alt", chars = "∞" },
  { key = "Key6",  mods = "Alt", chars = "§" },
  { key = "Key7",  mods = "Alt", chars = "¶" },
  { key = "Key8",  mods = "Alt", chars = "•" },
  { key = "Key9",  mods = "Alt", chars = "ª" },
]


[debug]
persistent_logging = false
log_level = "Off"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.9


[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 25
y = 20


[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Command"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
